#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Dec 24 19:27:46 +03 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 84e988b0217048268e1a0588a48078c7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_comparator_behav xil_defaultlib.tb_comparator -log elaborate.log"
xelab -wto 84e988b0217048268e1a0588a48078c7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_comparator_behav xil_defaultlib.tb_comparator -log elaborate.log

